from django.contrib import admin
from . models import *

admin.site.register(Registration)
admin.site.register(Category)
admin.site.register(Course)
admin.site.register(Chapter)
admin.site.register(Content)
admin.site.register(Enrollment)
admin.site.register(Learning_progress)
admin.site.register(Feedback)
admin.site.register(Messages)
admin.site.register(Guest_messages)
admin.site.register(Exam)
admin.site.register(Exam_results)
admin.site.register(Blogs)
admin.site.register(Requests)
admin.site.register(Newsletter)
admin.site.register(Attendance)
admin.site.register(Live)
admin.site.register(Assignment)
admin.site.register(Assignment_result)
admin.site.register(Exam_register)
admin.site.register(Course_st_stop)

