# Generated by Django 5.0.7 on 2024-09-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_remove_exam_lock_remove_exam_time_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_register',
            name='ex_reg_st_enroll',
        ),
    ]
