# Generated by Django 5.0.7 on 2024-09-20 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_remove_exam_register_ex_reg_st_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_register',
            name='ex_reg_tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register_teacher', to='learn.exam'),
        ),
    ]
