# Generated by Django 5.0.7 on 2024-09-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_alter_exam_register_ex_reg_tea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_register',
            name='ex_reg_cou',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam_register',
            name='ex_reg_st',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam_register',
            name='ex_reg_tea',
            field=models.IntegerField(null=True),
        ),
    ]
