# Generated by Django 5.0.7 on 2024-09-21 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_exam_register_ex_reg_cou_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_register',
            name='Time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exam_register',
            name='Time_stop',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exam_register',
            name='ex_reg_st',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register', to='learn.registration'),
        ),
    ]
