# Generated by Django 5.0.7 on 2024-09-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_alter_exam_register_time_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_register',
            name='ex_reg_st',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_register', to='learn.registration'),
        ),
        migrations.AlterField(
            model_name='exam_register',
            name='ex_reg_tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea_register', to='learn.registration'),
        ),
    ]
