# Generated by Django 5.0.7 on 2024-09-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_alter_exam_register_ex_reg_st_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_register',
            name='Ex_date',
            field=models.DateField(null=True),
        ),
    ]
