# Generated by Django 5.0.7 on 2024-09-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_exam_register_ex_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_register',
            name='ex_reg_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_register', to='learn.course'),
        ),
    ]
